In [1]:
import numpy as np

A = np.array([[0,1],[2,3],[4,5]])
B = np.array([[0,1,2,3],[4,5,6,7]])

result = np.dot(A,B)

print("行列積の結果：")
print(result)

max_value = np.max(result)

print("行列積の結果の最大値:", max_value)

行列積の結果：
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
行列積の結果の最大値: 47
